# SwiftLint Configuration for Pluckr
# This file configures SwiftLint rules for the project

# Disable all rules by default
disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - large_tuple
  - unused_import
  - unused_private_declaration
  - unused_setter_value
  - unused_optional_binding
  - unused_enumerated
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_declaration
  - unused_import
  - unused_optional_binding
  - unused_setter_value
  - unused_private_declaration
  - unused_enumerated
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_declaration
  - unused_import
  - unused_optional_binding
  - unused_setter_value
  - unused_private_declaration
  - unused_enumerated
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_declaration

# Enable specific rules
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Custom rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20

# Custom rules
custom_rules:
  # Ensure proper documentation for public APIs
  documented_public_api:
    name: "Documented Public API"
    regex: "^(public|open)\\s+(class|struct|enum|protocol|func|var|let)"
    message: "Public APIs should be documented"
    severity: warning

# Exclude specific files/directories
excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData
  - *.generated.swift
  - Utils/Documentation.swift  # Template file

# Include specific file patterns
included:
  - Sources
  - Tests

# Analyzer rules
analyzer_rules:
  - unused_declaration
  - unused_import
  - unused_private_declaration
  - unused_setter_value
  - unused_optional_binding
  - unused_enumerated
  - unused_closure_parameter
  - unused_control_flow_label

# Reporter configuration
reporter: "xcode" 